services:
 php:
  container_name: meu_php
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./php/www:/var/www/html
  depends_on:
   - db  

 db:
  image: mysql:8.0
  container_name: meu_bd_php
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=phprs
   - MYSQL_DATABASE=phprs
